### PR TITLE
Adding contexts for theme/background issues

### PR DESCRIPTION
**Pull request by Tsiou**
Added top-level context to the application that wrap the index data and provides current theme & background color value to all it's children.

FixedPlugin now has the ability to change the theme via the context.
Sidebar now uses the context passed in to get the current background color.

Used wrapper components for the contexts to avoid polluting index.js, and used hooks since the components were simple enough to not require any lifecycle methods etc.

Let me know if there's any changes that should be made to the commits.

adds #17

### CODE REVIEW

**Comment by einazare** [comment]
Hello there, @Tsiou ,

Thank you very much for this PR.
I've read the description and took a quick look through the files.
I'll make some testing tomorrow or Friday, and if it's all good, I'll merge the PR, if there are things that will require changes, I will come back here.

Once again, thank you for this awesome PR.

Best,
Manu

**Comment by Tsiou** [comment]
Hello @EINazare 

I pushed some other minor commits to the branch, mostly changed items with bootstrap classes into reactstrap components. Let me know if you need me to change something or if I should revert anything. No functionality was changed in the 5 extra commits.

Thanks.

**Comment by Tsiou** [comment]
Hello.
 
Since it's been a while, I was wondering, are you planning on accepting the changes or should I close the pull request? 
Is there something missing or something incorrectly changed?
Let me know so that I can take the necessary action.

Thanks.

**Comment by einazare** [comment]
Hello again, @Tsiou ,

No no, please leave the PR opened and I'll check it on Monday.
I've had to update some of our other products while finishing my Master's Degree and did not have time to check this PR :(.
Really sorry about this.

Please leave it open and if everything checks out on Monday, I'll accept it, if not I'll leave here some comments.

Best,
Manu

**Comment by einazare** [comment]
Hello there, @Tsiou ,

Just took a look at the code.
There is just one small issue, the line from the upper part of the pages does not change with the new context addition.
Let me know when you've solved this.
Screen Shot 2020-06-22 at 9 50 28 AM
Screen Shot 2020-06-22 at 9 50 35 AM



Best,
Manu

**Comment by Tsiou** [comment]
I fixed it the original way it was implemented, with a data attribute on the main-wrapper itself.
As an alternative, Admin.js could pass a data-border-color attribute or something similar to the main-wrapper div. The change would be 

```javascript
<div
 className="main-panel"
 ref={this.mainPanel}
 data-border-color={color}
>
```
on Admin.js, line 129

and 

```css
.main-panel[data-border-color="blue"] {
 border-top: 2px solid #1d8cf8;
}
.main-panel[data-border-color="green"] {
 border-top: 2px solid #00f2c3;
}
.main-panel[data-border-color="primary"] {
 border-top: 2px solid #e14eca;
}
```
on black-dashboard-react.css, line 10932
or on _sidebar-and-main-panel.scss, line 449

I can push another commit with the changes depending on which solution you prefer.

**Pull request merged**
